spring:
  profiles:
    active: local # ??? ??(H2)? ??

management:
  endpoints:
    web:
      exposure:
        include: health # ?? ?? ????? ?? ??

logging:
  level:
    root: INFO
    com.cloud.assignment: DEBUG # ?? ???? ??? ? ??? ?? ??